#!/usr/bin/env bash
set -ef -o pipefail
#set -x

if [ -z "$JENKINS_HOST" ]; then
  echo "** ERROR **: Please run this command again using either of the below commands:"
  echo ""
  echo "Generate list of plugins with specified version:"
  echo " JENKINS_HOST=user:password@localhost:8000 ./generate-plugins"
  echo ""
  echo "Generate list of plugins and use latest version available:"
  echo " JENKINS_HOST=user:password@localhost:8000 ./generate-plugins latest"

  exit 1
fi

if [ "$1" = "latest" ]; then
  echo "** Generating plugins list with latest versions"
  curl -sSL "http://$JENKINS_HOST/pluginManager/api/xml?depth=1&xpath=/*/*/shortName|/*/*/version&wrapper=plugins" | perl -pe 's/.*?<shortName>([\w-]+).*?<version>([^<]+)()(<\/\w+>)+/\1 \2\n/g'|sed 's/ /:/' | awk -F ":" '{ print $1 ":latest" }' >> ../files/plugins.txt
else
  echo "** Generating plugins list with current (pinned) versions"
  curl -sSL "http://$JENKINS_HOST/pluginManager/api/xml?depth=1&xpath=/*/*/shortName|/*/*/version&wrapper=plugins" | perl -pe 's/.*?<shortName>([\w-]+).*?<version>([^<]+)()(<\/\w+>)+/\1 \2\n/g'|sed 's/ /:/' >> ../files/plugins.txt
fi
