#cloud-config
hostname: ${hostname}
fqdn: ${fqdn}
manage_etc_hosts: true
package_upgrade: false
#users: []
random_seed:
  file: '/dev/urandom'
  command: ['sh', '-c', '(ec2metadata && date +%s%3N) | sha256sum > /dev/urandom']
  command_required: True
locale: en_GB.UTF-8
apt_preserve_sources_list: true
apt_sources:
 - source: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
   key: |
      -----BEGIN PGP PUBLIC KEY BLOCK-----

      mQINBFit2ioBEADhWpZ8/wvZ6hUTiXOwQHXMAlaFHcPH9hAtr4F1y2+OYdbtMuth
      lqqwp028AqyY+PRfVMtSYMbjuQuu5byyKR01BbqYhuS3jtqQmljZ/bJvXqnmiVXh
      38UuLa+z077PxyxQhu5BbqntTPQMfiyqEiU+BKbq2WmANUKQf+1AmZY/IruOXbnq
      L4C1+gJ8vfmXQt99npCaxEjaNRVYfOS8QcixNzHUYnb6emjlANyEVlZzeqo7XKl7
      UrwV5inawTSzWNvtjEjj4nJL8NsLwscpLPQUhTQ+7BbQXAwAmeHCUTQIvvWXqw0N
      cmhh4HgeQscQHYgOJjjDVfoY5MucvglbIgCqfzAHW9jxmRL4qbMZj+b1XoePEtht
      ku4bIQN1X5P07fNWzlgaRL5Z4POXDDZTlIQ/El58j9kp4bnWRCJW0lya+f8ocodo
      vZZ+Doi+fy4D5ZGrL4XEcIQP/Lv5uFyf+kQtl/94VFYVJOleAv8W92KdgDkhTcTD
      G7c0tIkVEKNUq48b3aQ64NOZQW7fVjfoKwEZdOqPE72Pa45jrZzvUFxSpdiNk2tZ
      XYukHjlxxEgBdC/J3cMMNRE1F4NCA3ApfV1Y7/hTeOnmDuDYwr9/obA8t016Yljj
      q5rdkywPf4JF8mXUW5eCN1vAFHxeg9ZWemhBtQmGxXnw9M+z6hWwc6ahmwARAQAB
      tCtEb2NrZXIgUmVsZWFzZSAoQ0UgZGViKSA8ZG9ja2VyQGRvY2tlci5jb20+iQI3
      BBMBCgAhBQJYrefAAhsvBQsJCAcDBRUKCQgLBRYCAwEAAh4BAheAAAoJEI2BgDwO
      v82IsskP/iQZo68flDQmNvn8X5XTd6RRaUH33kXYXquT6NkHJciS7E2gTJmqvMqd
      tI4mNYHCSEYxI5qrcYV5YqX9P6+Ko+vozo4nseUQLPH/ATQ4qL0Zok+1jkag3Lgk
      jonyUf9bwtWxFp05HC3GMHPhhcUSexCxQLQvnFWXD2sWLKivHp2fT8QbRGeZ+d3m
      6fqcd5Fu7pxsqm0EUDK5NL+nPIgYhN+auTrhgzhK1CShfGccM/wfRlei9Utz6p9P
      XRKIlWnXtT4qNGZNTN0tR+NLG/6Bqd8OYBaFAUcue/w1VW6JQ2VGYZHnZu9S8LMc
      FYBa5Ig9PxwGQOgq6RDKDbV+PqTQT5EFMeR1mrjckk4DQJjbxeMZbiNMG5kGECA8
      g383P3elhn03WGbEEa4MNc3Z4+7c236QI3xWJfNPdUbXRaAwhy/6rTSFbzwKB0Jm
      ebwzQfwjQY6f55MiI/RqDCyuPj3r3jyVRkK86pQKBAJwFHyqj9KaKXMZjfVnowLh
      9svIGfNbGHpucATqREvUHuQbNnqkCx8VVhtYkhDb9fEP2xBu5VvHbR+3nfVhMut5
      G34Ct5RS7Jt6LIfFdtcn8CaSas/l1HbiGeRgc70X/9aYx/V/CEJv0lIe8gP6uDoW
      FPIZ7d6vH+Vro6xuWEGiuMaiznap2KhZmpkgfupyFmplh0s6knymuQINBFit2ioB
      EADneL9S9m4vhU3blaRjVUUyJ7b/qTjcSylvCH5XUE6R2k+ckEZjfAMZPLpO+/tF
      M2JIJMD4SifKuS3xck9KtZGCufGmcwiLQRzeHF7vJUKrLD5RTkNi23ydvWZgPjtx
      Q+DTT1Zcn7BrQFY6FgnRoUVIxwtdw1bMY/89rsFgS5wwuMESd3Q2RYgb7EOFOpnu
      w6da7WakWf4IhnF5nsNYGDVaIHzpiqCl+uTbf1epCjrOlIzkZ3Z3Yk5CM/TiFzPk
      z2lLz89cpD8U+NtCsfagWWfjd2U3jDapgH+7nQnCEWpROtzaKHG6lA3pXdix5zG8
      eRc6/0IbUSWvfjKxLLPfNeCS2pCL3IeEI5nothEEYdQH6szpLog79xB9dVnJyKJb
      VfxXnseoYqVrRz2VVbUI5Blwm6B40E3eGVfUQWiux54DspyVMMk41Mx7QJ3iynIa
      1N4ZAqVMAEruyXTRTxc9XW0tYhDMA/1GYvz0EmFpm8LzTHA6sFVtPm/ZlNCX6P1X
      zJwrv7DSQKD6GGlBQUX+OeEJ8tTkkf8QTJSPUdh8P8YxDFS5EOGAvhhpMBYD42kQ
      pqXjEC+XcycTvGI7impgv9PDY1RCC1zkBjKPa120rNhv/hkVk/YhuGoajoHyy4h7
      ZQopdcMtpN2dgmhEegny9JCSwxfQmQ0zK0g7m6SHiKMwjwARAQABiQQ+BBgBCAAJ
      BQJYrdoqAhsCAikJEI2BgDwOv82IwV0gBBkBCAAGBQJYrdoqAAoJEH6gqcPyc/zY
      1WAP/2wJ+R0gE6qsce3rjaIz58PJmc8goKrir5hnElWhPgbq7cYIsW5qiFyLhkdp
      YcMmhD9mRiPpQn6Ya2w3e3B8zfIVKipbMBnke/ytZ9M7qHmDCcjoiSmwEXN3wKYI
      mD9VHONsl/CG1rU9Isw1jtB5g1YxuBA7M/m36XN6x2u+NtNMDB9P56yc4gfsZVES
      KA9v+yY2/l45L8d/WUkUi0YXomn6hyBGI7JrBLq0CX37GEYP6O9rrKipfz73XfO7
      JIGzOKZlljb/D9RX/g7nRbCn+3EtH7xnk+TK/50euEKw8SMUg147sJTcpQmv6UzZ
      cM4JgL0HbHVCojV4C/plELwMddALOFeYQzTif6sMRPf+3DSj8frbInjChC3yOLy0
      6br92KFom17EIj2CAcoeq7UPhi2oouYBwPxh5ytdehJkoo+sN7RIWua6P2WSmon5
      U888cSylXC0+ADFdgLX9K2zrDVYUG1vo8CX0vzxFBaHwN6Px26fhIT1/hYUHQR1z
      VfNDcyQmXqkOnZvvoMfz/Q0s9BhFJ/zU6AgQbIZE/hm1spsfgvtsD1frZfygXJ9f
      irP+MSAI80xHSf91qSRZOj4Pl3ZJNbq4yYxv0b1pkMqeGdjdCYhLU+LZ4wbQmpCk
      SVe2prlLureigXtmZfkqevRz7FrIZiu9ky8wnCAPwC7/zmS18rgP/17bOtL4/iIz
      QhxAAoAMWVrGyJivSkjhSGx1uCojsWfsTAm11P7jsruIL61ZzMUVE2aM3Pmj5G+W
      9AcZ58Em+1WsVnAXdUR//bMmhyr8wL/G1YO1V3JEJTRdxsSxdYa4deGBBY/Adpsw
      24jxhOJR+lsJpqIUeb999+R8euDhRHG9eFO7DRu6weatUJ6suupoDTRWtr/4yGqe
      dKxV3qQhNLSnaAzqW/1nA3iUB4k7kCaKZxhdhDbClf9P37qaRW467BLCVO/coL3y
      Vm50dwdrNtKpMBh3ZpbB1uJvgi9mXtyBOMJ3v8RZeDzFiG8HdCtg9RvIt/AIFoHR
      H3S+U79NT6i0KPzLImDfs8T7RlpyuMc4Ufs8ggyg9v3Ae6cN3eQyxcK3w0cbBwsh
      /nQNfsA6uu+9H7NhbehBMhYnpNZyrHzCmzyXkauwRAqoCbGCNykTRwsur9gS41TQ
      M8ssD1jFheOJf3hODnkKU+HKjvMROl1DK7zdmLdNzA1cvtZH/nCC9KPj1z8QC47S
      xx+dTZSx4ONAhwbS/LN3PoKtn8LPjY9NP9uDWI+TWYquS2U+KHDrBDlsgozDbs/O
      jCxcpDzNmXpWQHEtHU7649OXHP7UeNST1mCUCH5qdank0V1iejF6/CfTFU4MfcrG
      YT90qFF93M3v01BbxP+EIY2/9tiIPbrd
      =0YYh
      -----END PGP PUBLIC KEY BLOCK-----
 - source: "deb [arch=amd64] http://www.mirrorservice.org/sites/archive.ubuntu.com/ubuntu xenial main restricted universe multiverse"
 - source: "deb [arch=amd64] http://www.mirrorservice.org/sites/archive.ubuntu.com/ubuntu xenial-security main restricted universe multiverse"
 - source: "deb [arch=amd64] http://www.mirrorservice.org/sites/archive.ubuntu.com/ubuntu xenial-updates main restricted universe multiverse"
   key: |
      -----BEGIN PGP PUBLIC KEY BLOCK-----
      Version: GnuPG v1.4.11 (GNU/Linux)

      mQINBFh/VTQBEADFpYb7HGNNtXnkyDZ6mbcuEwff+5LYApjsPooyKqDrdHW8PP8a
      vS9fANKR9Sb5gNSXucjQe4PVVY28VkIbheLQFNkWcilw238x8Z9GY45wPCz09IxB
      p1iXB3FSH33cdiITddgP4NhnNnazBYWhmnERSL4fOEF9xZfX4nRdmDFdRheLG6Tl
      I3b6ydQKLIehTiyJz+DCCt9+PR4SmIZC0b3vlX/dGUY582FEv1oULJUDkFf6PqSt
      MMWB7O2Ybidy+DNdkIzWrsxi89D2QReNs1Q3ICJyc1suiH0gD2U1Hxo4wxMdId/5
      HWgNf4MXTu0gSRhJd2DYBeAr+DR5vb/1AogWoZGJIwADjEihFqj52IO4pNv+G6+m
      tACnKBcvVjq/bwi3XDZ3nmngzGm7IyDIe4fb+NUzuGs6tZIykyrBDQ2WdVZUvKwj
      PUH3cTe+q/Jy8TjQ5NmiwEukR/6FLyHYjCFmWMsPp3ZWtBwaEfoItZ0+JqjjRmLM
      k3n9G6W1kOVcxsKDpdwWGtt8D+H0eSyTNzM3dfkr9hyR2uW2jdRWg6DDRALL+N1O
      UYMBPk+A0wEsx7AaYo9OYjvVgwzfY/c+VQDO5NgP2Olv/dWr4DAu9PJFJth9goab
      YUhmaEdAmymsEXwZhQ1HWSKJA+JT4MwwMgCczPmERwXe+NMKZtTo5Ucb/QARAQAB
      tEdJREFQIFJlbGVhc2UgU2lnbmluZyBLZXkgPGlkYS1vcGVyYXRpb25zQGRpZ2l0
      YWwuY2FiaW5ldC1vZmZpY2UuZ292LnVrPokCPgQTAQIAKAUCWH9VNAIbAwUJAgIp
      AAYLCQgHAwIGFQgCCQoLBBYCAwECHgECF4AACgkQYtvW/ix+RYrXOA//Z60OwRbG
      +kHd4anCL4nAhrSdZfR75QIggCFUZbSXmkjRGQLW5kdkBjyQUAP43AgL55Rs0fRf
      OTmAFQH0ad1awXS7IiRWVNR4Jc56ER6GFA8dYKX7jTf/NeYddHgTS2v86HCNQJt0
      YNFM5wWDUnCzmU9+js7mfc6jx4RiCC7VLRBrpul2MmSgpFcZ3kG6k39W6bTdmDaW
      vs1lsc4pVrS9XyW3SoMcCOGRaJ4KnK4u5zKp+3LIPhZW4Y0Qa/f1K+VFnYQp+N6i
      Cu4sZIt9TzlLGVGMaFzkKMGEHD5QabrDHqoA+GojcmpUyoz91O467q4s/Fra+2/o
      7o9Ou42lODAmnsHKfFIo4mIkrJXU/CSO88vnwnXTzYCTVdheSxPdhRXwgkHDp0SK
      aCqgVW7Z7DTVpVA7DaI9oDZXuxBVB9jINXi8loLLLO7uJ2Wp7J5PMhoekYi0u727
      5AoEm5VoWBmASpQMGTcogRDqByGUUX0Svza0km+4rfeuGeiIp1EWJqGT/t/l3vFF
      8QPqKz2d02vtHTgPJstuL/Rsf8xngn5LtWSMytqDyAZFWOwibg97g5nfYzewYo9I
      B5PVlNIZOTscoiF67G4JQ/zDKBHzLYAHJncFRsyJIM/Q0/Gz6kdwWUM0az/CGDH+
      OiqNfQTp8G02nSNiteGrWchqw1fgoG/KmhS5Ag0EWH9VNAEQALlli7fDn6+DnSQC
      cNiFD5X7dlEYmJ5LQazeXwW8VuB/lTYZjoeZvZVNWz5ZICe/GSQ7aC3fhDwmIZTG
      xpcKtAe6CkQmrg3VJjaZxK6sJUxjRFNDfLPl446Y44BE067BIFleYkdldm5MS2r3
      QJmAiFh5rpL01s6dp08lb8RkIaonb4WL/st/dZinKgJ6OvmjTkTvOYqL3tYh1Vgo
      3PHIcMqw8ZzxvRprWzUpEpU4O1niOz/z0d1pkuIK4pbfcZVXrBQIazwo1F7aU0Rg
      4p7JLinDg9VBNKouvl6sD21nKtEXzCr0DxOgtVJFZrk98KNxzLQoiMl/QGQncDUi
      yc+zBTpgTyC6YmDx/USmClx6Yu48mcgpznm9BadkhZ7dnb+RG3u0miwYdaYBii6f
      YY2vDuaAR5Nn8u7oUqqfzobGdYC3cuGeoxuFyyEPLtrw4eusbkoUuVZ+SXZ5/i3Z
      of7OQ9Javlwqd8xWgi6saWF8pRiByk0osxMK1kSlL1nRELiFWiAIs8S1+QB6lseF
      eilJD3D+seCyNI3QA8GJJkOxN33+VroOiTDfeg/ozAB52tBcCzk/qFiT6jVau7p6
      WZeT0bRxe2qxoD2k3V0NhXUHvXnFab32fXvTaIPYR0WSi9BOcQVoS+KiPo8n3fy0
      qIZWWfudsl2wX7P7U1FsyEP2Cg+hABEBAAGJAiUEGAECAA8FAlh/VTQCGwwFCQIC
      KQAACgkQYtvW/ix+RYqFTg//XQ8MRqWpqyLAjCVuV4s2OTXIbbGeMZ5xV94/8RjU
      Ropu+ZjHOQjoGJpGA76glIuxZ9I3Ju2GV1PDtqA4tb7X7P5WoW/mVV7LPGDJj7SJ
      OrxiALIn+XLFMmXjxqpIo6l/HtBVSoTw+yB0bCzcdUEyHKcgV7uqOvzRuMwCP/rd
      PGs1WEvYZuCcwJGbEMnwInO/scyGw2Jbo/1LdpipXdATkOZ4QOozMol8VPG/MTgV
      HcPzn1BD51Eq5lcYEh8LOwiC/ernx/b1ylEKeal3fktfRPNvzgj6K3XTaK9hvPDx
      WZ6AUA1faVOzrFsllIFoR4vKjIhInpWuUfQFlqEHsc9DG7dIl2ERR4YSB/8hLPOr
      wWQhO5eCgK7V91MxLkeVoiRM+wrOPLKvV5pySt7jylx8uyDFrPHg89WBbSRikjOv
      /X8kECniL+sBxWYvzzohMGtj1k2eGBYZzxw0QO62XZj/+pIzsL2Km8a6KD5W/Euq
      5Mz2ku7G81uJ7DsiivyzWXDD/Hdm3x7+gFth9W4Bfjnem8U+oYsZtcw2NwGX/6QQ
      jFRycd7C3jPGFS6zl3VGd3PdQH6SAKv/oyKiu1sJvbDrzFUpezkJaRO3NpMFwO6q
      UQYzL3+9ZNiEWHo1+hdKk+EbsssnjvP12DWFjR+12RCS9TdTAlSCLQ9bBBj3Oudj
      v6c=
      =ExQY
      -----END PGP PUBLIC KEY BLOCK-----
      -----BEGIN PGP PUBLIC KEY BLOCK-----
      Version: GnuPG v1.4.11 (GNU/Linux)

      mQINBFZq7x8BEACkhrM76JyYEf5Y2BcHh2pI0D9Is7JcBjoXos3wSGsKI3qaMh+s
      tXz/g0QmYs5XJAWtM1Y2Lrh5HOMekhrgx4Y+SdFDKIYXM299CfhI7pvJFapgpF1l
      mB4MlOgQUINDK7Q2nlCGrpJhH7rgHo8u04m63GUXQx37SMCiT1VrZGKdL90XYR1d
      k5Ws+OnLAwl69RqQVK99CKtVac8AJyXbyoURDthWVEUO8r0Yu7k8uCG9keCUlB80
      GL9zoF5gMucAMahhO/s3Z16VIVAeJfeaMPiPJ9j+JYpgp7lODmFV45zQh77enZDs
      gH0kQAzsDfGUw1t0qaudvXjEkZSq5RbFYpWVXG7dfVHdx8F05Xu5uMgf9NwJcKM+
      6D53uXF6Jqn7JGiqC0r4kMOeaW7qu8RUNbnz0gPjrexgUq2asyPxxISgxz2L4K7T
      OJyP1JIaEPr74seGSlPZxFO/RMOyNc2ygl5Y8+vt79SkcQ5RxVc5Agt8BYWjbISX
      jRw/73C2dh5dRBa7qnJrLpM5kN31tnhMhn3VaLOFHmdilq6YWJCr5mpIsL01bUEQ
      f1WXkU3XBGDyjFkHyjYEHVr9cf/KGJSLDJNfh06r6XsX81vpO5SEMdid0/+M8RTT
      bFjf9NMerk3mb9+oilIm0hNc3igL9JWhtmniOBLbCZFoh3T0aHHyHrGnxQARAQAB
      tEdJREFQIFJlbGVhc2UgU2lnbmluZyBLZXkgPGlkYS1vcGVyYXRpb25zQGRpZ2l0
      YWwuY2FiaW5ldC1vZmZpY2UuZ292LnVrPokCPgQTAQIAKAUCVmrvHwIbAwUJAim2
      AAYLCQgHAwIGFQgCCQoLBBYCAwECHgECF4AACgkQfKCX666YnNu7WhAAhmura8rX
      wBlCalQkT+lYqHfytQYz7LUQXiN0fvVDeUX09YdCZM4a/GdubhzHZaHvAvX/Ey+e
      HoWQHEMr0WS62qeG1FpJtAWXCcP7LrdG84MPAO9KCUBB9/X924FIE7dHXQ/SahMp
      mNBkjje8GSI/inolT6FkIHWWAeeel2+gGYOBrn7cTc5ZK22oIJe5vxQumt+S5N7e
      tjfC3butWElyjRENBmiZxl/fzO5DYMyvkNjixiPREXBNgd+48j9ozJYkQi3SZxIh
      67fXaSHVhv5E8RS0rEPHxUwnqvb3tbFzMlzz0LueuOwU08V2QWw8/Xw2509o6jO8
      6EHUpUp81+4Co5KSSbgZj0K4ELv73Y/tDt20wxNAz254SdM13c7dczwJpSTY+nmi
      f6DLdTi3HUkFggRLj7GDzts/IZ8PLF0OEr+gfyTpZc4wsEN+9DHleAS0dZmq3hM+
      Fg+JbRfSubtU+HCYHMACTbSILkSSYuCENBgtLJa3Np4vsBiwrA1uKtcQjk5yQjrO
      Exi+SucMyjC0v46ZL1+AuOTSpSk7D8nLJazkgzX2KBJB/aa+K4TwjcjPiQdQbmqQ
      l1HFyGXoCPRw6TcgujwFcBbgY2VFBN7l4wC6gaM2MZf1JgDJByFXrGdIGfg02X0Y
      UmejpnE4XWaha9H2aSMT2TciABIe2JRH5Ym5Ag0EVmrvHwEQAKaabRZCVHTs/7dZ
      8dayJhf5JDxBMorKwxMkBYy7puFYOg4XR7yiMsQmwLkaKulr0YoeeB0jsLfAcxCO
      BUP71FymA5IgnyqGq7Q6upH9wP4srvlY7Uq6HdEbBvMGhiWBwPd0RS91h41qiP1C
      gYKbDz/llHlpZ5BkRfZ0eer3rlgbd1kPeNIlAnlyS33/ALJydCYxWSMHM2glyej7
      62X3M8yuTVpcrEk3WGCefMY9JG+AO5IGkgD7Z/+Hzd9XP27jS+AjLEbxGHZpTwq2
      5RFlRsj6amEIJrq41LXtEqq/GMH/4AEECNsN/fjugSgV+t2N5P/OeT5LvfynFImm
      Q0nWeX1lkPVURFzKuj8fvpvTbeYN1in9k7UQXHNS2+pbnA6r6V1qnwBfu6S53mc0
      9KLaQ4geuQwQpam711vLdp7++tp3Q76udnAivQ0gzrswnWNGHHZKG4PR7fhDFS3S
      nw0suXYzDvVCWzLhU0xzhqXkU0YMWHqh4YWVbiyCxXSALYOMcE6wEOY3gWUOUjt2
      Agoze8IfXGq1cSWKJsEjxoibSxuuoavtH3fylsUOiGM+9J7X1DejrNLut35ykSUr
      uT52Ma3y6RGftJVDWaCIPkJrB3hhHqvFTzOK+5t9yN/g222rWJndVOwsNPVOc6qI
      PMjkZ1arYegdNY2BMt7oJFALOL0/ABEBAAGJAiUEGAECAA8FAlZq7x8CGwwFCQIp
      tgAACgkQfKCX666YnNtvEw/9E0S5I0GAQPRPUNvEtkoPvgOiLaiS+9eRjMWBe4+Q
      TyVWYWdmqctIneC+ckjfaxqXP7Ycyj9rEnTBUti+utVDbqBhR1ne2ci1/W/5RS/g
      HrNMMNxP10JI0fGzshL5OqTUNLJAQltj9Gq8vRgBgd9BIDdPQazoWzKxj83me37S
      aa35lVjMpBeHMUPI8lcJKkWUG100ZRIq4+shaLsnU46hRizxS4S1ty16FunDz2Bl
      ZWGvrrRXEDL4PscdgRZrTUzbdUASG83Uzwuqym7C3pnqrRrpr/Kj1geGMGRCyMpI
      0g3EncYQ4YUdJ+JNLafPoxanF6He+XexIy488eQNNEUgrYu4KhitkGF9Mr0E9ELe
      SEK9oEOtl4YCgDkRyewRT75Z6PdqF894xdw095BRGHhkmIY8q5zqUgtoAtx9Dm5j
      viEw8QzEAhnevI2fJbKfYNe7ootic90CPP0cFCDYDI6GY5PxwdM1BgxOPKxaBsWo
      /IfBSYhr13RizWYcgxH0dliUunvNTdlqAgwPpx6Z1A5WyecbN4eO4rNtCFgtb36t
      73XbNwi/9DXG4OoXLJwlmW1fE0+rzAQnZWDVurNDxGZLnN8MCa75sVXBamuDcU4i
      3bDYa6HwokmJh8daornm9K6Nn9nFWJtg571pOhFjGqK9Ih4DdEU1n1vcU3tMJHQV
      9m8=
      =0TfX
      -----END PGP PUBLIC KEY BLOCK-----
write_files:
  - content: |
      {
        "hosts": ["tcp://0.0.0.0:2375", "unix:///var/run/docker.sock"]
      }
    path: /tmp/daemon.json
    owner: root:root
    permissions: '0644'
  - content: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/dockerd
    path: /tmp/override.conf
    owner: root:root
    permissions: '0644'
bootcmd:
  - [ sh, -c, echo "Starting Jenkins2 Worker Server" ]
runcmd:
  - [ apt-get, update ]
  - [ apt-get, upgrade ]
  - apt-get install -y docker-ce=${dockerversion}
  - [ service, docker, stop ]
  - [ mkdir, -p, /etc/systemd/system/docker.service.d ]
  - [ mv, /tmp/daemon.json, /etc/docker ]
  - [ mv, /tmp/override.conf, /etc/systemd/system/docker.service.d/override.conf ]
  - [ systemctl, daemon-reload ]
  - [ service, docker, start ]
